version: 2.1

jobs:
  build-dashboard:
    working_directory: /project  
    docker:
      - image: docker/compose:1.25.0-rc2-debian
    steps:
      - run:
          name: Configure environment
          command: |
            apt-get update
            apt-get install git -y
      - setup_remote_docker
      - checkout
      - run:
          name: Docker build 
          command: |
            docker-compose build

workflows:
  build:
    jobs:
      - build-dashboard
